# Generated by Django 3.2.15 on 2022-10-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowtrack',
            name='malign_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rowtrack',
            name='malignant_stereotypes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rowtrack',
            name='misogyny_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rowtrack',
            name='pornography_count',
            field=models.IntegerField(default=0),
        ),
    ]
